name: counter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true